### ISSUE TITLE
Big files on npm

### ISSUE THREAD

**Issue by benkaiser** [dscape/clarinet#40]
Hello!

Thanks for the awesome project.
I am currently using your repository (as a dependency of one of my dependencies) in a project of mine, and am packaging it for multiple platforms, however the clarinet folder is 36MB on disk and it all get's automatically packaged! Would you perhaps consider `.npmignore`ing `test/*` and `samples/*`? As they aren't needed as part of using the library and as such doesn't make sense requiring all devs download them to their environments, and in my case, my users downloading them in a binary.

**Comment by finnp** [comment]
+1

**Comment by retrohacker** [comment]
It looks like an `.npmignore` was merged in back in May: https://github.com/dscape/clarinet/blob/master/.npmignore

But a release hasn't been cut since. Would it be possible to get a `0.11.1` out that uses the `.npmignore`?

**Comment by kapouer** [comment]
Why closing this @evan-king ? The package in npm is still HUGE. Even in big projects i'm using, the 25MB of samples is just crazy.

**Comment by evan-king** [comment]
Because it's already "resolved" in the sense that the fix is in master and assigned to a ready-to-release milestone.  I've been lax in actually publishing to NPM and will do so soon, but would rather not tempt Murphy during the holiday season.
