### ISSUE TITLE
Using createStream() parser does not fire end() event when readstream compeletes.

### ISSUE THREAD

**Issue by markddrake** [dscape/clarinet#54]
created a parser using clarinet.createStream(). Invoked it using Pipe. Got the end event for my topmost object and the end event for the readstrea but did not get an end event from parser,  and my promise that resolved from the parsers end event never completes.. Am I missing something here...

**Comment by evan-king** [comment]
Can you provide a minimal script to demonstrate this behavior?

**Comment by evan-king** [comment]
the `onend` hook belongs to the CParser, not the CStream, which still follows the Streams API.  What you want here is just
```js
p.on('end',function(){console.log('Parser: end');});
```
for the parse stream the same way you do for the read stream.
