### ISSUE TITLE
Question... Can I pause the event Stream...

### ISSUE THREAD

**Issue by markddrake** [dscape/clarinet#55]
I have a situation where I need to some significant processing after reaching the end of a particular object. This processing must complete before I can process the remaining objects in the file. Is there a way from within the onend... methods to pause and resume event generation, I've tried unpipe and pipe on the readstream that is feeding the parser but this doesn't seem to have the desired affect ( presumably the parser already has a buffer full of data to process)

**Comment by evan-king** [comment]
Unless I'm misunderstanding something, you can just feed the parsed objects into another stream and do your processing there.  Your transform stream will just work as desired (ordered handling of incoming objects, opportunity for shared state which I presume you need for subsequent objects, and backpressure handled by the Streams API - or you can pause the consuming stream explicitly if needed but I don't think it should be).

**Comment by markddrake** [comment]
Thx... Trying that approach now...

**Comment by markddrake** [comment]
It seems to work reasonably well.. However I'm now encountering other problems / limitations
