### ISSUE TITLE
Parser Line value seems to be incorrect in certain edge cases

### ISSUE THREAD

**Issue by ZackingIt** [dscape/clarinet#69]
With larger, deeply nested JSONs, that have been JSON.stringified (to prettify/autoformat the JSON) the parser line value appears to be off:  it is incrementing in situations even where there is no `\n` newline value.

I was able to solve this by doing `parser.line -= 1` in `parser.onclosearray` and `parser.oncloseobject`, but this issue probably deserves addressing without a manual fix.  A cursory review of the clarinet.js source file suggests that we are simply incrementing when we encounter a new LineFeed (i.e., \n), so the code doesn't look immediately wrong, and I'm perplexed by what could be causing this.

Alternatively, if I've grossly misused the library somehow, that would be great to know too!

As an example case, try printing out `parser.line` in every single event callback (i.e., parser.onopenobject and parser.onvalue) for this -- you will see some line number discrepancies if you don't do line adjustments.
```
{
	"a": {
		"b": 5
	},
	"c": {
		"d": {
			"e": 1
		},
		"f": [
			7,
			8,
			9
		],
		"g": 5
	}
}
```

**Comment by Kevinicus37** [comment]
I've had the same issue, though @ZackingIt solution didn't completely solve the problem. Subtracting a line on onclosearray and oncloseobject still had it off quite a bit. Doing it only on oncloseobject gets it fairly close, but there are still some areas it can be off. It appears the the location of the error, in regards to it being on the same line as an object closing, and whether or not it is before it or after it on the line seems to play a role. However, I haven't been able to really figure out what exactly is going on.
